# # Resolve react_native_pods.rb with node to allow for hoisting
# require Pod::Executable.execute_command('node', ['-p',
#   'require.resolve(
#     "react-native/scripts/react_native_pods.rb",
#     {paths: [process.argv[1]]},
#   )', __dir__]).strip

# platform :ios, min_ios_version_supported
# prepare_react_native_project!

# linkage = ENV['USE_FRAMEWORKS']
# if linkage != nil
#   Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
#   use_frameworks! :linkage => linkage.to_sym
# end

# target 'PlateApp' do
#   config = use_native_modules!

#   use_react_native!(
#     :path => config[:reactNativePath],
#     :app_path => "#{Pod::Config.instance.installation_root}/..",
#     :hermes_enabled => true
#   )

#   # Firebase, GoogleMaps, FastImage 등만 선언!
#   pod 'Firebase', :modular_headers => true
#   pod 'FirebaseCore', :modular_headers => true
#   pod 'FirebaseMessaging', :modular_headers => true
#   pod 'GoogleUtilities', :modular_headers => true
#   pod 'GoogleMaps'
#   pod 'Google-Maps-iOS-Utils'
#   pod 'react-native-maps', :path => '../node_modules/react-native-maps'
# end

# post_install do |installer|
#   react_native_post_install(
#     installer,
#     "react-native",
#     :mac_catalyst_enabled => false,
#   )
#   installer.pods_project.targets.each do |target|
#     if target.name.include?('FastImage')
#       target.build_configurations.each do |config|
#         config.build_settings['HEADER_SEARCH_PATHS'] ||= '$(inherited)'
#         config.build_settings['HEADER_SEARCH_PATHS'] << ' $(PODS_ROOT)/Headers/Private'
#         config.build_settings['HEADER_SEARCH_PATHS'] << ' $(PODS_ROOT)/Headers/Private/React-Core'
#         config.build_settings['HEADER_SEARCH_PATHS'] << ' $(PODS_ROOT)/Headers/Public'
#         config.build_settings['HEADER_SEARCH_PATHS'] << ' $(PODS_ROOT)/Folly'
#       end
#     end
#   end
# end


# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, '16.0'
prepare_react_native_project!

# (옵션) CocoaPods 동작 안정화
install! 'cocoapods',
  :warn_for_multiple_pod_sources => false,
  :warn_for_unused_master_specs_repo => false

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'PlateApp' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # 절대 경로로 앱 루트 지정
    :app_path => "#{Pod::Config.instance.installation_root}/..",
    :hermes_enabled => false
  )

  # ✅ Firebase/Google 일부를 modular_headers로 명시 (충돌 방지)
  pod 'Firebase',            :modular_headers => true
  pod 'FirebaseCore',        :modular_headers => true
  pod 'FirebaseMessaging',   :modular_headers => true
  pod 'GoogleUtilities',     :modular_headers => true

  # 기존 설정
  pod 'GoogleMaps'
  pod 'Google-Maps-iOS-Utils'
  pod 'react-native-maps', :path => '../node_modules/react-native-maps'
end

# ✅ 모든 Pod 타깃에 iOS 최소 버전 강제 (빌드 오류 해결 핵심)
post_install do |installer|
  react_native_post_install(
    installer,
    Pod::Config.instance.installation_root.join('..').to_path,
    :mac_catalyst_enabled => false
  )

  installer.generated_projects.each do |project|
    project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '16.0'
      end
    end
  end
end
