default_platform(:ios)

app_store_connect_api_key(
  key_id: "NW2M42KU3S",
  issuer_id: "4327d55b-0013-4bae-82d5-766e184ff5f7",
  key_filepath: "./fastlane/AuthKey_NW2M42KU3S.p8"
)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    match(
      type: "appstore",
      readonly: false
    )

    build_app(
      workspace: "PlateApp.xcworkspace",
      scheme: "PlateApp",
      export_method: "app-store"
    )

    upload_to_testflight
  end
end
