# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

api_key = app_store_connect_api_key(
  key_id: "NW2M42KU3S",
  issuer_id: "4327d55b-0013-4bae-82d5-766e184ff5f7",
  key_filepath: "./fastlane/AuthKey_NW2M42KU3S.p8",
  duration: 1200,
  in_house: false
)

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    increment_build_number(xcodeproj: "PlateApp.xcodeproj")

    build_app(
      workspace: "PlateApp.xcworkspace",
      scheme: "PlateApp",
      export_method: "app-store",
      export_options: {
        signingStyle: "automatic",
        compileBitcode: false,
        manageAppVersionAndBuildNumber: false
      },
      xcargs: "-allowProvisioningUpdates"
    )


    upload_to_testflight(api_key: api_key)
  end
end
